---
controller_credentials:
- name: Redis Cluster Password - profile_redis_cluster
  description: Credential for profile_redis_cluster
  organization: Default
  credential_type: Redis Cluster Password
  update_secrets: true
  inputs:
    redis_password: '{{ vault_redis_password }}'
