---
controller_credential_types:
- name: Redis Cluster Password
  description: Credential type for Redis Cluster Password
  kind: cloud
  inputs:
    fields:
    - id: redis_password
      type: string
      label: Redis Password
      secret: true
      help_text: Password used for Redis cluster authentication
    required:
    - redis_password
  injectors:
    extra_vars:
      redis_password: !unsafe '{{ redis_password }}'
