---
controller_credentials:
- name: PostgreSQL Database - profile_app_stack
  description: Credential for profile_app_stack
  organization: Default
  credential_type: PostgreSQL Database
  update_secrets: true
  inputs:
    db_user: '{{ db_user }}'
    db_password: '{{ vault_db_password }}'
- name: Application Secret Key - profile_app_stack
  description: Credential for profile_app_stack
  organization: Default
  credential_type: Application Secret Key
  update_secrets: true
  inputs:
    secret_key: '{{ vault_secret_key }}'
- name: HAProxy Statistics - profile_app_stack
  description: Credential for profile_app_stack
  organization: Default
  credential_type: HAProxy Statistics
  update_secrets: true
  inputs:
    stats_user: '{{ stats_user }}'
    stats_password: '{{ vault_stats_password }}'
- name: Redis Authentication - profile_app_stack
  description: Credential for profile_app_stack
  organization: Default
  credential_type: Redis Authentication
  update_secrets: true
  inputs:
    redis_password: '{{ vault_redis_password }}'
