---
- name: Include Redis role from eloy.redis collection
  ansible.builtin.include_role:
    name: eloy.redis.redis
  vars:
    redis_port: "{{ redis_port }}"
    redis_requirepass: "{{ redis_password }}"
    redis_maxmemory: "{{ maxmemory_mb }}mb"
    redis_maxmemory_policy: "{{ maxmemory_policy }}"
    redis_cluster_enabled: true
    redis_aof_enabled: true
    redis_appendfsync: everysec
    redis_rdb_enabled: true
    redis_save:
      - 900 1
      - 300 10
      - 60 10000
    redis_bind: 0.0.0.0
