---
- name: Create facts.d directory
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: "0755"
- name: Deploy HAProxy version fact
  ansible.builtin.copy:
    src: facts.d/haproxy_version.fact
    dest: /etc/ansible/facts.d/haproxy_version.fact
    owner: root
    group: root
    mode: "0755"
- name: Re-read facts
  ansible.builtin.setup:
    filter: ansible_local
