---
controller_credentials:
- name: HAProxy Stats Password - profile_haproxy
  description: eyaml PKCS7-encrypted HAProxy statistics page password, must be decrypted
    and re-encrypted with Ansible Vault
  organization: Default
  credential_type: HAProxy Stats Password
  update_secrets: true
  inputs:
    stats_user: '{{ stats_user }}'
    stats_password: '{{ vault_stats_password }}'
